//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtcSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtcSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplicationExitButtonLabel {
            get {
                return ResourceManager.GetString("ApplicationExitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is setting to associate the &apos;.atc&apos; file to the AttacheCase application... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Associating {
            get {
                return ResourceManager.GetString("Associating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association Complete successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssociationComplete {
            get {
                return ResourceManager.GetString("AssociationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssociationFailed {
            get {
                return ResourceManager.GetString("AssociationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association with files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AssociationSettingsButtonLabel {
            get {
                return ResourceManager.GetString("AssociationSettingsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypted file of &apos;AttacheCase&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;AttacheCase.exe&quot; is not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogMessageAttacheCaseNotFound {
            get {
                return ResourceManager.GetString("DialogMessageAttacheCaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting of Association files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelAssociation {
            get {
                return ResourceManager.GetString("LabelAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The executable file is not found that associated to the extension. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TheAppNotFound {
            get {
                return ResourceManager.GetString("TheAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is setting to Unassociate the &apos;.atc&apos; file in the AttacheCase application... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnAssociating {
            get {
                return ResourceManager.GetString("UnAssociating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnAssociation Complete successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnAssociationComplete {
            get {
                return ResourceManager.GetString("UnAssociationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings of UnAssociation failed to be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnAssociationFailed {
            get {
                return ResourceManager.GetString("UnAssociationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnAssociation with files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnAssociationSettingsButtonLabel {
            get {
                return ResourceManager.GetString("UnAssociationSettingsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the encypted file in AttacheCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string verbDescription {
            get {
                return ResourceManager.GetString("verbDescription", resourceCulture);
            }
        }
    }
}
