//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttacheCase.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttacheCase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AttacheCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttacheCase {
            get {
                return ResourceManager.GetString("AttacheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextBack {
            get {
                return ResourceManager.GetString("ButtonTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextOK {
            get {
                return ResourceManager.GetString("ButtonTextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To enable this setting, you will need to restart the AttacheCase.
        ///Do you restart AttacheCase now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageApplicationRestart {
            get {
                return ResourceManager.GetString("DialogMessageApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This encrypted file is broken. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageAtcFileBroken {
            get {
                return ResourceManager.GetString("DialogMessageAtcFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both Random setting and Zero setting are not able to set to zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageBothRandomAndZeroNotZero {
            get {
                return ResourceManager.GetString("DialogMessageBothRandomAndZeroNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is invalid, or the encrypted file might have been broken. Decryption is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDecryptionError {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in decryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDecryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the encypted file(s) that are the source of the decryption? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDeleteEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDeleteEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the files and folders that are the source of the encrypted file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDeleteOriginalFilesAndFolders {
            get {
                return ResourceManager.GetString("DialogMessageDeleteOriginalFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder to save is not found! Process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDirectoryNotFount {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are files or folders that be encrypted or decrypted, and they are mixed, they does not exists. So, AttacheCase can not determine which should encrypt or decrypt either. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDragAndDropMixedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDragAndDropMixedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageEncryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageEncryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It contains the executable files in the decrypted file.
        ///Do you run the following file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageExecutableFile {
            get {
                return ResourceManager.GetString("DialogMessageExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association was successful に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool can be not launched. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationToolNotLaunched {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal file index is invalid in encrypted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileIndexInvalid {
            get {
                return ResourceManager.GetString("DialogMessageFileIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders are not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFilesNotFoundDelete {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders that move to trash is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFilesNotFoundMoveToTrash {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File disassociation was successful. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileUnAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileUnAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because you are using the temporary settings from the command line option, it will not be able to reflect the change of main setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagefTemporarySettings {
            get {
                return ResourceManager.GetString("DialogMessagefTemporarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file has been encrypted with a higher version.
        ///It can not be decrypted. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageHigherVersion {
            get {
                return ResourceManager.GetString("DialogMessageHigherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No free space on the disk. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNoDiskSpace {
            get {
                return ResourceManager.GetString("DialogMessageNoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not encrypted file. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotAtcFile {
            get {
                return ResourceManager.GetString("DialogMessageNotAtcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not use the folder to the password file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotDirectoryInPasswordFile {
            get {
                return ResourceManager.GetString("DialogMessageNotDirectoryInPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not the same hash value. Whether the file is corrupted, it may have been made the falsification.The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotSameHash {
            get {
                return ResourceManager.GetString("DialogMessageNotSameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following characters cannot be used for the file name of Windows.
        ///
        ///\\ / : , * ? \&quot; &lt; &gt; | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotUseWindowsFileName {
            get {
                return ResourceManager.GetString("DialogMessageNotUseWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There decrypted file is {0} or more.
        ///But, open all of the files associated with application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageOpenMultipleFiles {
            get {
                return ResourceManager.GetString("DialogMessageOpenMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is not found that specified in setting panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagePasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two Passwords do not match, it is invalid.
        ///Input them again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagePasswordsNotMatch {
            get {
                return ResourceManager.GetString("DialogMessagePasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected decrypted files. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageUnexpectedDecryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedDecryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. And stops processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageUnexpectedError {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleAlert {
            get {
                return ResourceManager.GetString("DialogTitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input encrypted file name for putting together に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleAllPackFiles {
            get {
                return ResourceManager.GetString("DialogTitleAllPackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleCommandLine {
            get {
                return ResourceManager.GetString("DialogTitleCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select files to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleEncryptSelectFiles {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleEncryptSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleInfomation {
            get {
                return ResourceManager.GetString("DialogTitleInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleRegistry {
            get {
                return ResourceManager.GetString("DialogTitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Password file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSelectPasswordFile {
            get {
                return ResourceManager.GetString("DialogTitleSelectPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSettings {
            get {
                return ResourceManager.GetString("DialogTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory to which you save the file or folder to decrypt always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToDecryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the encrypted file always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToEncryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the zip file with password always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToZipFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionCanceled {
            get {
                return ResourceManager.GetString("labelCaptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionCompleted {
            get {
                return ResourceManager.GetString("labelCaptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionError {
            get {
                return ResourceManager.GetString("labelCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password does not match, it is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionPasswordInvalid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password matches, it is valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionPasswordValid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following directory already exists. Do you overwrite the directory to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelComfirmToOverwriteDir {
            get {
                return ResourceManager.GetString("labelComfirmToOverwriteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following file already exists. Do you overwrite the files to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelComfirmToOverwriteFile {
            get {
                return ResourceManager.GetString("labelComfirmToOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured during complete deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeleteError {
            get {
                return ResourceManager.GetString("labelCompleteDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete deleting files or folder has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeleteFileCanceled {
            get {
                return ResourceManager.GetString("labelCompleteDeleteFileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders complete deleting is completed normally. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeletingCompleted {
            get {
                return ResourceManager.GetString("labelCompleteDeletingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted Completely. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompletelyDeleteCompleted {
            get {
                return ResourceManager.GetString("labelCompletelyDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Default&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressDefault {
            get {
                return ResourceManager.GetString("labelCompressDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Maximum&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressMaximum {
            get {
                return ResourceManager.GetString("labelCompressMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;None&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressNone {
            get {
                return ResourceManager.GetString("labelCompressNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelDecyptionCanceled {
            get {
                return ResourceManager.GetString("labelDecyptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred when deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelDeleteError {
            get {
                return ResourceManager.GetString("labelDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values of WinZipAes128 and WinZipAes256 are not part of the Zip specification, but rather imply the use of a vendor-specific extension from WinZip. If you want to produce interoperable Zip archives, do not use these values. For example, if you produce a zip archive using WinZipAes256, you will be able to open it in Windows Explorer on Windows XP and Vista, but you will not be able to extract entries; trying this will lead to an &quot;unspecified error&quot;. For this reason, some people have said that a zip archive t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptAlgoDescriptionAES {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PkzipWeak implies the use of Zip 2.0 encryption, which is known to be weak and subvertible. 
        ///
        ///A note on interoperability: Values of PkzipWeak and None are specified in PKWARE&apos;s zip specification, and are considered to be &quot;standard&quot;. Zip archives produced using these options will be interoperable with many other zip tools and libraries, including Windows Explorer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptAlgoDescriptionPkzipWeak {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionPkzipWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptionCanceled {
            get {
                return ResourceManager.GetString("labelEncryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for decryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelGettingReadyForDecryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelGettingReadyForEncryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input password again to confirm: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelInputPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("labelInputPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Completely に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labellabelCompletelyDelete {
            get {
                return ResourceManager.GetString("labellabelCompletelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrash {
            get {
                return ResourceManager.GetString("labelMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrashCanceled {
            get {
                return ResourceManager.GetString("labelMoveToTrashCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash was completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrashCompleted {
            get {
                return ResourceManager.GetString("labelMoveToTrashCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Deleting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDelete {
            get {
                return ResourceManager.GetString("labelNormalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDeleteCanceled {
            get {
                return ResourceManager.GetString("labelNormalDeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDeleteCompleted {
            get {
                return ResourceManager.GetString("labelNormalDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordFile {
            get {
                return ResourceManager.GetString("labelPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password file is entered already: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordFileIsEnteredAlready {
            get {
                return ResourceManager.GetString("labelPasswordFileIsEnteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The memorized password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordMemorized {
            get {
                return ResourceManager.GetString("labelPasswordMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password of command line option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordOfCommandLineOption {
            get {
                return ResourceManager.GetString("labelPasswordOfCommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete completely is completed successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessGettingRedyForEncryption {
            get {
                return ResourceManager.GetString("labelProcessGettingRedyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDecrypt {
            get {
                return ResourceManager.GetString("labelProcessNameDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDelete {
            get {
                return ResourceManager.GetString("labelProcessNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting Completely... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessNameDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameEncrypt {
            get {
                return ResourceManager.GetString("labelProcessNameEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameMoveToTrash {
            get {
                return ResourceManager.GetString("labelProcessNameMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting updates information is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelCheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("linkLabelCheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for update... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelCheckingForUpdates {
            get {
                return ResourceManager.GetString("linkLabelCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your version is latest. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelLatestVersion {
            get {
                return ResourceManager.GetString("linkLabelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest version is released! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelLatestVersionReleased {
            get {
                return ResourceManager.GetString("linkLabelLatestVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogFilterAllFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon files(*.ico)|*.ico|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogFilterIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Icon files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogTitleIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogTitleIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ATC files (*.atc)|*.atc|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogFilterAtcFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterAtcFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INI files (*.ini)|*.ini|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogFilterIniFilles {
            get {
                return ResourceManager.GetString("SaveDialogFilterIniFilles", resourceCulture);
            }
        }
    }
}
