//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttacheCase.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttacheCase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AttachéCase#3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AttachéCase#3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AttacheCase {
            get {
                return ResourceManager.GetString("AttacheCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextBack {
            get {
                return ResourceManager.GetString("ButtonTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTextOK {
            get {
                return ResourceManager.GetString("ButtonTextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access to the file has been denied.
        ///Move to a place (eg Desktop) where you can read and write files and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageAccessDeny {
            get {
                return ResourceManager.GetString("DialogMessageAccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To enable this setting, you will need to restart the AttacheCase.
        ///Do you restart AttacheCase now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageApplicationRestart {
            get {
                return ResourceManager.GetString("DialogMessageApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This encrypted file is broken. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageAtcFileBroken {
            get {
                return ResourceManager.GetString("DialogMessageAtcFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both Random setting and Zero setting are not able to set to zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageBothRandomAndZeroNotZero {
            get {
                return ResourceManager.GetString("DialogMessageBothRandomAndZeroNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because it exceeded the limit number of inputting password, the encrypted file has been broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageBroken {
            get {
                return ResourceManager.GetString("DialogMessageBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The encrypted file has already been destroyed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageBrokenAlready {
            get {
                return ResourceManager.GetString("DialogMessageBrokenAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The broken token could not found. The file may not be an encrypted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageBrokenDestroyNotFount {
            get {
                return ResourceManager.GetString("DialogMessageBrokenDestroyNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypted data not found. The file is broken.
        ///Decryption failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDataNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is invalid, or the encrypted file might have been broken. Decryption is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDecryptionError {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in decryption. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDecryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageDecryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the encypted file(s) that are the source of the decryption? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDeleteEncryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDeleteEncryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to delete the files and folders that are the source of the encrypted file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDeleteOriginalFilesAndFolders {
            get {
                return ResourceManager.GetString("DialogMessageDeleteOriginalFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder to save is not found! Process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDirectoryNotFount {
            get {
                return ResourceManager.GetString("DialogMessageDirectoryNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are files or folders that be encrypted or decrypted, and they are mixed, they does not exists. So, AttacheCase can not determine which should encrypt or decrypt either. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageDragAndDropMixedFiles {
            get {
                return ResourceManager.GetString("DialogMessageDragAndDropMixedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified password file is not found in encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageEncryptionPasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessageEncryptionPasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It contains the executable files in the decrypted file.
        ///Do you run the following file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageExecutableFile {
            get {
                return ResourceManager.GetString("DialogMessageExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association was successful に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File association tool can be not launched. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileAssociationToolNotLaunched {
            get {
                return ResourceManager.GetString("DialogMessageFileAssociationToolNotLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal file index is invalid in encrypted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileIndexInvalid {
            get {
                return ResourceManager.GetString("DialogMessageFileIndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file in the following specified file&apos;s list can not be found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileInFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileInFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The character encoding of the following specified list file is unknown that can not be read! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileListEncodingUnknown {
            get {
                return ResourceManager.GetString("DialogMessageFileListEncodingUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following specified list file can not be found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileListNotFound {
            get {
                return ResourceManager.GetString("DialogMessageFileListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders are not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFilesNotFoundDelete {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders that move to trash is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFilesNotFoundMoveToTrash {
            get {
                return ResourceManager.GetString("DialogMessageFilesNotFoundMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File disassociation was successful. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageFileUnAssociationSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageFileUnAssociationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because you are using the temporary settings from the command line option, it will not be able to reflect the change of main setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagefTemporarySettings {
            get {
                return ResourceManager.GetString("DialogMessagefTemporarySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file has been encrypted with a higher version.
        ///It can not be decrypted. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageHigherVersion {
            get {
                return ResourceManager.GetString("DialogMessageHigherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path of files or folders are invalid. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageInvalidFilePath {
            get {
                return ResourceManager.GetString("DialogMessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No free space on the disk. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNoDiskSpace {
            get {
                return ResourceManager.GetString("DialogMessageNoDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not encrypted file. The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotAtcFile {
            get {
                return ResourceManager.GetString("DialogMessageNotAtcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not use the folder to the password file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotDirectoryInPasswordFile {
            get {
                return ResourceManager.GetString("DialogMessageNotDirectoryInPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is not the same hash value. Whether the file is corrupted, it may have been made the falsification.The process is aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotSameHash {
            get {
                return ResourceManager.GetString("DialogMessageNotSameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following characters cannot be used for the file name of Windows.
        ///
        ///\\ / : , * ? \&quot; &lt; &gt; | に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotUseWindowsFileName {
            get {
                return ResourceManager.GetString("DialogMessageNotUseWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now does not correspond to the decryption of password-protected ZIP file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNotZipDecrypted {
            get {
                return ResourceManager.GetString("DialogMessageNotZipDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting of Windows XP compatibility mode could not be completed. If Setting is not completed, the application can not be started.
        ///Please start again from the beginning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageNoXpCompatiblityMode {
            get {
                return ResourceManager.GetString("DialogMessageNoXpCompatiblityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There decrypted file is {0} or more.
        ///But, open all of the files associated with application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageOpenMultipleFiles {
            get {
                return ResourceManager.GetString("DialogMessageOpenMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is not found that specified in setting panel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagePasswordFileNotFound {
            get {
                return ResourceManager.GetString("DialogMessagePasswordFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two Passwords do not match, it is invalid.
        ///Input them again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessagePasswordsNotMatch {
            get {
                return ResourceManager.GetString("DialogMessagePasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup tool is not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageSetupToolNotFound {
            get {
                return ResourceManager.GetString("DialogMessageSetupToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected decrypted files. It stopped the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageUnexpectedDecryptedFiles {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedDecryptedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. And stops processing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogMessageUnexpectedError {
            get {
                return ResourceManager.GetString("DialogMessageUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleAlert {
            get {
                return ResourceManager.GetString("DialogTitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input encrypted file name for putting together に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleAllPackFiles {
            get {
                return ResourceManager.GetString("DialogTitleAllPackFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleCommandLine {
            get {
                return ResourceManager.GetString("DialogTitleCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select files to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleEncryptSelectFiles {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder to encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleEncryptSelectFolder {
            get {
                return ResourceManager.GetString("DialogTitleEncryptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleInfomation {
            get {
                return ResourceManager.GetString("DialogTitleInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleRegistry {
            get {
                return ResourceManager.GetString("DialogTitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Password file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSelectPasswordFile {
            get {
                return ResourceManager.GetString("DialogTitleSelectPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogTitleSettings {
            get {
                return ResourceManager.GetString("DialogTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory to which you save the file or folder to decrypt always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToDecryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToDecryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the encrypted file always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToEncryptedFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToEncryptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the folder to save the zip file with password always. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string folderBrowserDialogSaveToZipFile {
            get {
                return ResourceManager.GetString("folderBrowserDialogSaveToZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionAborted {
            get {
                return ResourceManager.GetString("labelCaptionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skipped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionAllSkipped {
            get {
                return ResourceManager.GetString("labelCaptionAllSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionCanceled {
            get {
                return ResourceManager.GetString("labelCaptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionCompleted {
            get {
                return ResourceManager.GetString("labelCaptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionError {
            get {
                return ResourceManager.GetString("labelCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password does not match, it is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionPasswordInvalid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password matches, it is valid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCaptionPasswordValid {
            get {
                return ResourceManager.GetString("labelCaptionPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following directory already exists. Do you overwrite the directory to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelComfirmToOverwriteDir {
            get {
                return ResourceManager.GetString("labelComfirmToOverwriteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following file already exists. Do you overwrite the files to save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelComfirmToOverwriteFile {
            get {
                return ResourceManager.GetString("labelComfirmToOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occured during complete deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeleteError {
            get {
                return ResourceManager.GetString("labelCompleteDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete deleting files or folder has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeleteFileCanceled {
            get {
                return ResourceManager.GetString("labelCompleteDeleteFileCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files or folders complete deleting is completed normally. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompleteDeletingCompleted {
            get {
                return ResourceManager.GetString("labelCompleteDeletingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted Completely. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompletelyDeleteCompleted {
            get {
                return ResourceManager.GetString("labelCompletelyDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Default&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressDefault {
            get {
                return ResourceManager.GetString("labelCompressDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Maximum&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressMaximum {
            get {
                return ResourceManager.GetString("labelCompressMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;None&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelCompressNone {
            get {
                return ResourceManager.GetString("labelCompressNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelDecyptionCanceled {
            get {
                return ResourceManager.GetString("labelDecyptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred when deleting files or folders. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelDeleteError {
            get {
                return ResourceManager.GetString("labelDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values of WinZipAes128 and WinZipAes256 are not part of the Zip specification, but rather imply the use of a vendor-specific extension from WinZip. If you want to produce interoperable Zip archives, do not use these values. For example, if you produce a zip archive using WinZipAes256, you will be able to open it in Windows Explorer on Windows XP and Vista, but you will not be able to extract entries; trying this will lead to an &quot;unspecified error&quot;. For this reason, some people have said that a zip archive t [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptAlgoDescriptionAES {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionAES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PkzipWeak implies the use of Zip 2.0 encryption, which is known to be weak and subvertible. 
        ///
        ///A note on interoperability: Values of PkzipWeak and None are specified in PKWARE&apos;s zip specification, and are considered to be &quot;standard&quot;. Zip archives produced using these options will be interoperable with many other zip tools and libraries, including Windows Explorer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptAlgoDescriptionPkzipWeak {
            get {
                return ResourceManager.GetString("labelEncryptAlgoDescriptionPkzipWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelEncryptionCanceled {
            get {
                return ResourceManager.GetString("labelEncryptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for decryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelGettingReadyForDecryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelGettingReadyForEncryption {
            get {
                return ResourceManager.GetString("labelGettingReadyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input password again to confirm: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelInputPasswordAgainToConfirm {
            get {
                return ResourceManager.GetString("labelInputPasswordAgainToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid character string in path. Do you replace it and decrypt it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelInvalidChar {
            get {
                return ResourceManager.GetString("labelInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Completely に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labellabelCompletelyDelete {
            get {
                return ResourceManager.GetString("labellabelCompletelyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrash {
            get {
                return ResourceManager.GetString("labelMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrashCanceled {
            get {
                return ResourceManager.GetString("labelMoveToTrashCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move files or folders to the trash was completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelMoveToTrashCompleted {
            get {
                return ResourceManager.GetString("labelMoveToTrashCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Deleting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDelete {
            get {
                return ResourceManager.GetString("labelNormalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files or folders has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDeleteCanceled {
            get {
                return ResourceManager.GetString("labelNormalDeleteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified files or folders has been deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelNormalDeleteCompleted {
            get {
                return ResourceManager.GetString("labelNormalDeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordFile {
            get {
                return ResourceManager.GetString("labelPasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password file is entered already: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordFileIsEnteredAlready {
            get {
                return ResourceManager.GetString("labelPasswordFileIsEnteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discard memorized password and input new password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordInputNewPassword {
            get {
                return ResourceManager.GetString("labelPasswordInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The memorized password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordMemorized {
            get {
                return ResourceManager.GetString("labelPasswordMemorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password of command line option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelPasswordOfCommandLineOption {
            get {
                return ResourceManager.GetString("labelPasswordOfCommandLineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete completely is completed successfully. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting ready for encryption... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessGettingRedyForEncryption {
            get {
                return ResourceManager.GetString("labelProcessGettingRedyForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDecrypt {
            get {
                return ResourceManager.GetString("labelProcessNameDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDelete {
            get {
                return ResourceManager.GetString("labelProcessNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting Completely... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameDeleteCompletely {
            get {
                return ResourceManager.GetString("labelProcessNameDeleteCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encypting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameEncrypt {
            get {
                return ResourceManager.GetString("labelProcessNameEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to Trash... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string labelProcessNameMoveToTrash {
            get {
                return ResourceManager.GetString("labelProcessNameMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting updates information is failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelCheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("linkLabelCheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for update... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelCheckingForUpdates {
            get {
                return ResourceManager.GetString("linkLabelCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your version is latest. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelLatestVersion {
            get {
                return ResourceManager.GetString("linkLabelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The latest version is released! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string linkLabelLatestVersionReleased {
            get {
                return ResourceManager.GetString("linkLabelLatestVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogFilterAllFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon files(*.ico)|*.ico|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogFilterIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogFilterIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Icon files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenDialogTitleIconFiles {
            get {
                return ResourceManager.GetString("OpenDialogTitleIconFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ATC files (*.atc)|*.atc|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogFilterAtcFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterAtcFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INI files (*.ini)|*.ini|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogFilterIniFilles {
            get {
                return ResourceManager.GetString("SaveDialogFilterIniFilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Self Executable file(*.exe)|*.exe|All files(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveDialogFilterSelfExeFiles {
            get {
                return ResourceManager.GetString("SaveDialogFilterSelfExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vulnerable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabel00 {
            get {
                return ResourceManager.GetString("zxcvbnLabel00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabel01 {
            get {
                return ResourceManager.GetString("zxcvbnLabel01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Somewhat weak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabel02 {
            get {
                return ResourceManager.GetString("zxcvbnLabel02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabel03 {
            get {
                return ResourceManager.GetString("zxcvbnLabel03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strong に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabel04 {
            get {
                return ResourceManager.GetString("zxcvbnLabel04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnLabelEmpty {
            get {
                return ResourceManager.GetString("zxcvbnLabelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add another word or two. Uncommon words are better. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAddAnotherWordOrTwo {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAddAnotherWordOrTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All-uppercase is almost as easy to guess as all-lowercase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAllCapsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAllCapsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid dates and years that are associated with you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAvoidDatesYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidDatesYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid repeated words and characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAvoidRepeatedWordsAndChars {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidRepeatedWordsAndChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid sequences. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAvoidSequences {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Avoid recent years. Avoid years that are associated with you. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionAvoidYearsAssociatedYou {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionAvoidYearsAssociatedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capitalization doesn&apos;t help very much. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionCapsDontHelp {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionCapsDontHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a few words, avoid common phrases. No need for symbols, digits, or uppercase letters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionDefault {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionEmpty {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Predictable substitutions like &apos;@&apos; instead of &apos;a&apos; don&apos;t help very much. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionPredictableSubstitutionsEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionPredictableSubstitutionsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reversed words aren&apos;t much harder to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionReversedWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionReversedWordEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use a longer keyboard pattern with more turns. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnSuggestionUseLongerKeyboardPattern {
            get {
                return ResourceManager.GetString("zxcvbnSuggestionUseLongerKeyboardPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnToolTipTitleSuggestions {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnToolTipTitleWarning {
            get {
                return ResourceManager.GetString("zxcvbnToolTipTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dates are often easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarnigDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarnigDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common names and surnames are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningCommonNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a very common password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dates are often easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningDatesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningDatesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningDefault {
            get {
                return ResourceManager.GetString("zxcvbnWarningDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty String. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningEmpty {
            get {
                return ResourceManager.GetString("zxcvbnWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Names and surnames by themselves are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningNameSurnamesEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningNameSurnamesEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent years are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningRecentYearsEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRecentYearsEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &apos;aaa&apos; are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAaaEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAaaEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeats like &apos;abcabcabc&apos; are only slightly harder to guess than &apos;abc&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningRepeatsLikeAbcSlighterHarder {
            get {
                return ResourceManager.GetString("zxcvbnWarningRepeatsLikeAbcSlighterHarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sequences like abc or 6543 are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningSequenceAbcEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningSequenceAbcEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Short keyboard patterns are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningShortKeyboardPatterns {
            get {
                return ResourceManager.GetString("zxcvbnWarningShortKeyboardPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is similar to a commonly used password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningSimilarCommonPasswords {
            get {
                return ResourceManager.GetString("zxcvbnWarningSimilarCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Straight rows of keys are easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningStraightRow {
            get {
                return ResourceManager.GetString("zxcvbnWarningStraightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a top-10 common password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningTop10Passwords {
            get {
                return ResourceManager.GetString("zxcvbnWarningTop10Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A word by itself is easy to guess. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string zxcvbnWarningWordEasy {
            get {
                return ResourceManager.GetString("zxcvbnWarningWordEasy", resourceCulture);
            }
        }
    }
}
